server:
  port: 8989
  tomcat:
    connection-timeout: 60000
    remoteip:
      remote-ip-header: X-Real-IP
      protocol-header: X-Forwarded-Proto

spring:
  datasource:
    url: jdbc:mysql://192.168.232.0:3306/qd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: your_password
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

mybatis-plus:
  mapper-locations: classpath:/Mapper/*.xml
  type-aliases-package: com.sicnu.wzh.Entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
